x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: Host=postgresql;Port=5432;Database=currencytracker_dev;Username=postgres;Password=admin
  ASPNETCORE_HTTPS_PORT: ""

x-jwt-env: &jwt-env
  Jwt__SecretKey: cl7F4MnVp24VCH6tkCBCZ9aHJbklPMZnV7jrP7gTO38=
  Jwt__Issuer: CurrencyTracker
  Jwt__Audience: CurrencyTrackerUsers
  Jwt__ExpirationMinutes: 60

services:

  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: currencytracker_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d currencytracker_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  migrationservice:
    build:
      context: .
      dockerfile: MigrationService/MigrationService.Tool/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
    command: ["--migrate"]
    environment:
      <<: *common-env
    networks:
      - backend
    restart: "no"

  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      migrationservice:
        condition: service_completed_successfully
    environment:
      <<: [*common-env, *jwt-env]
      ASPNETCORE_URLS: http://+:8080
    networks:
      - backend
    restart: unless-stopped

  financeservice:
    build:
      context: .
      dockerfile: FinanceService/FinanceService.API/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      migrationservice:
        condition: service_completed_successfully
    environment:
      <<: [*common-env, *jwt-env]
      ASPNETCORE_URLS: http://+:8080
    networks:
      - backend
    restart: unless-stopped

  currencyworker:
    build:
      context: .
      dockerfile: CurrencyWorker/CurrencyWorker.Worker/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      migrationservice:
        condition: service_completed_successfully
    environment:
      <<: *common-env
      CurrencyUpdate__IntervalMinutes: 60
    networks:
      - backend
    restart: unless-stopped

  apigateway:
    build:
      context: .
      dockerfile: APIGateway/APIGateway/Dockerfile
    depends_on:
      - userservice
      - financeservice
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      <<: *jwt-env
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  backend:
    driver: bridge 